"""
This type stub file was generated by pyright.
"""

'''
Motion Event Factory
====================

Factory of :class:`~kivy.input.motionevent.MotionEvent` providers.
'''
__all__ = ('MotionEventFactory', )
class MotionEventFactory:
    '''MotionEvent factory is a class that registers all availables input
    factories. If you create a new input factory, you need to register
    it here::

        MotionEventFactory.register('myproviderid', MyInputProvider)

    '''
    __providers__ = ...
    @staticmethod
    def register(name, classname): # -> None:
        '''Register a input provider in the database'''
        ...
    
    @staticmethod
    def list(): # -> dict[Any, Any]:
        '''Get a list of all available providers'''
        ...
    
    @staticmethod
    def get(name): # -> None:
        '''Get a provider class from the provider id'''
        ...
    


