"""
This type stub file was generated by pyright.
"""

import os
import sysconfig
import sys
import traceback
import tempfile
import subprocess
import importlib
import kivy
from kivy.logger import Logger

'''
Core Abstraction
================

This module defines the abstraction layers for our core providers and their
implementations. For further information, please refer to
:ref:`architecture` and the :ref:`providers` section of the documentation.

In most cases, you shouldn't directly use a library that's already covered
by the core abstraction. Always try to use our providers first.
In case we are missing a feature or method, please let us know by
opening a new Bug report instead of relying on your library.

.. warning::
    These are **not** widgets! These are just abstractions of the respective
    functionality. For example, you cannot add a core image to your window.
    You have to use the image **widget** class instead. If you're really
    looking for widgets, please refer to :mod:`kivy.uix` instead.
'''
class CoreCriticalException(Exception):
    ...


def core_select_lib(category, llist, create_instance=..., base=..., basemodule=...):
    ...

def core_register_libs(category, libs, base=...): # -> list[Any] | None:
    ...

def handle_win_lib_import_error(category, provider, mod_name): # -> None:
    ...

